/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class http_demo_Search */

#ifndef _Included_http_demo_Search
#define _Included_http_demo_Search
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     http_demo_Search
 * Method:    initData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_http_demo_Search_initData
  (JNIEnv *, jobject);

/*
 * Class:     http_demo_Search
 * Method:    searchResults
 * Signature: ([Ljava/lang/String;)[Lhttp/demo/Result;f
 */
JNIEXPORT jobjectArray JNICALL Java_http_demo_Search_searchResults
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
